package com.example.retrofitdemo;

import java.util.List;

import retrofit2.Call;
import retrofit2.http.GET;

//3.  Represent API of web service in our app
public interface JsonPlaceholderApi {

    // getting data from https://jsonplaceholder.typicode.com/posts, where https://jsonplaceholder.typicode.com is base url
    // and posts is relative url
    @GET("posts") // telling retrofit to implement this method for getting posts data from api
    Call<List<Post>> getPost(); // code will be generated by retrofit to get list of post - response from API, JSON Obj

    // Call encapsulate a single request and response, we use it execute get request

}
